site_name: BiUH Wiki
theme: material

nav:
  - 首页: index.md
  - 常见问题汇总: faq.md
  - 住宿: dorm.md
  - 社团: clubs/clubs.md
  - 娱乐:
    - Minecraft: funs/minecraft.md
  - 交通:
    - 校园出行: transportation/campus.md
