site_name: 比科大生存指南
site_url: https://wiki.leak.moe/
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 首页: index.md
  - 常见问题汇总: faq/index.md
  - 住宿: dorm/index.md
  - 学业:
    - 提问的智慧: academic/smart-questions/index.md
    - 校历: academic/timetable/index.md
    - 出国:
      - 留学: academic/go-abroad/study-abroad.md
      - 志愿者: academic/go-abroad/volunteer.md
      - 冬夏校: academic/go-abroad/winter-summer-school.md
  - 学生组织:
    - 学生会: organizations/students-union/index.md
    - 社团: organizations/club/index.md
  - 娱乐:
    - Minecraft 社区服: play/minecraft.md
  - 交通:
    - 校园出行: transportation/campus.md

plugins:
  - search
  - glightbox:
      auto_caption: false

markdown_extensions:
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/beautiful-mermaid/dist/beautiful-mermaid.browser.global.js
  - js/render_mermaid.js

extra_css:
  - css/mermaid.css

extra:
  generator: false
